/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.7.0 (NJsonSchema v10.6.7.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// @ts-nocheck

export interface CategoryDto {
  categoryId?: number;
  name?: string | undefined;
}

export interface CreatePostRequest {
  title?: string | undefined;
  content?: string | undefined;
  categoryId?: number;
  isPublished?: boolean;
  image?: string | undefined;
  imageCaption?: string | undefined;
}

export interface CreateUserRequest {
  email?: string | undefined;
  password?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  phone?: string | undefined;
}

export interface ImageDto {
  imageData?: string | undefined;
  imagePath?: string | undefined;
  imageCaption?: string | undefined;
}

export interface LogInRequest {
  email?: string | undefined;
  password?: string | undefined;
}

export interface PostDto {
  readonly postId?: number;
  title?: string | undefined;
  content?: string | undefined;
  authorId?: string;
  authorName?: string | undefined;
  publishDate?: Date;
  isPublished?: boolean;
  categoryId?: number;
  categoryName?: string | undefined;
  imagePath?: string | undefined;
  readonly slug?: string | undefined;
}

export interface PostsRequest {
  skip?: number;
  take?: number;
  sorting?: string | undefined;
}

export interface UpdatePostRequest {
  postId?: number;
  title?: string | undefined;
  content?: string | undefined;
  categoryId?: number;
  isPublished?: boolean;
  image?: ImageDto;
}

export interface UpdateUserRequest {
  firstName?: string | undefined;
  lastName?: string | undefined;
}

export interface UserDto {
  readonly id?: string;
  readonly userName?: string | undefined;
  readonly firstName?: string | undefined;
  readonly lastName?: string | undefined;
}
